In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [2]:
data = pd.read_csv("data.csv")
data.head()

id  kpi1  kpi2  kpi3  kpi4  kpi5  kpi6  kpi7  kpi8  kpi9  kpi10  \
0  31468130376     0     0     0     1     0     1     0     0     0      1   
1  26390602610     0     0     0     1     0     0     1     0     1      0   
2  38364284432     0     1     0     0     1     0     0     0     0      1   
3  34159080018     1     0     0     0     0     1     0     0     1      0   
4  28348770458     0     0     0     1     0     1     0     0     0      1   

   kpi11  
0     38  
1     28  
2      3  
3     11  
4      1

In [3]:
target = pd.read_csv("target.csv")
target.head()

id  score             survey_date
0  24144248776      3  04/23/2019 12:00:00 AM
1  24144252836      3  04/16/2019 12:00:00 AM
2  24144293146      3  04/16/2019 12:00:00 AM
3  24144662644      2        04-04-2019 00:00
4  24144975572      2  04/24/2019 12:00:00 AM

In [4]:
data = pd.merge(data,target[["id","score"]],on='id')
data.head()

id  kpi1  kpi2  kpi3  kpi4  kpi5  kpi6  kpi7  kpi8  kpi9  kpi10  \
0  31468130376     0     0     0     1     0     1     0     0     0      1   
1  26390602610     0     0     0     1     0     0     1     0     1      0   
2  38364284432     0     1     0     0     1     0     0     0     0      1   
3  34159080018     1     0     0     0     0     1     0     0     1      0   
4  28348770458     0     0     0     1     0     1     0     0     0      1   

   kpi11  score  
0     38      2  
1     28      3  
2      3      3  
3     11      3  
4      1      3

In [5]:
data_kpis = data[['kpi1','kpi2','kpi3','kpi4','kpi5','kpi6','kpi7','kpi8','kpi9','kpi10','kpi11']].values
data_kpis[1]

array([ 0,  0,  0,  1,  0,  0,  1,  0,  1,  0, 28])

In [6]:
score = data['score'].values
score

array([2, 3, 3, ..., 3, 3, 3])

In [7]:
model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[11,])])

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [13]:
model.compile(optimizer='sgd', loss='mean_squared_error')

In [14]:
model.fit(data_kpis, score, epochs=10)

Train on 11274 samples
Epoch 1/10
11274/11274 [==============================] - 0s 43us/sample - loss: nan
Epoch 2/10
11274/11274 [==============================] - 0s 29us/sample - loss: nan
Epoch 3/10
11274/11274 [==============================] - 0s 29us/sample - loss: nan
Epoch 4/10
11274/11274 [==============================] - 0s 28us/sample - loss: nan
Epoch 5/10
11274/11274 [==============================] - 0s 28us/sample - loss: nan
Epoch 6/10
11274/11274 [==============================] - 0s 28us/sample - loss: nan
Epoch 7/10
11274/11274 [==============================] - 0s 29us/sample - loss: nan
Epoch 8/10
11274/11274 [==============================] - 0s 29us/sample - loss: nan
Epoch 9/10
11274/11274 [==============================] - 0s 28us/sample - loss: nan
Epoch 10/10
11274/11274 [==============================] - 0s 29us/sample - loss: nan


In [10]:
ind = np.array([[0,  0,  0,  1,  0,  0,  1,  0,  1,  0, 28]])
output = model.predict(ind)
output

array([[2.6175373]], dtype=float32)